name: Deploy Docs (MkDocs)

on:
  push:
    branches: [main]
    paths:
      - "notasdocs/**"

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install docs dependencies
        working-directory: notasdocs
        run: pip install -r requirements.txt

      - name: Deploy docs
        working-directory: notasdocs
        run: mkdocs gh-deploy --force