# Generated by Django 5.2.1 on 2025-09-03 19:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabado',
            fields=[
                ('id_sabado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('username', models.CharField(error_messages={'unique': 'Este Nombre de Usuario ya existe'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nombre de Usuario')),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
                ('rut', models.CharField(max_length=45, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=300)),
                ('rut_cliente', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('giro', models.CharField(blank=True, max_length=1000, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentFacturas',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('file_url', models.URLField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(default='NO PAGADO', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_facturas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('num_nota', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_despacho', models.DateTimeField()),
                ('estado_solicitud', models.CharField(default='No Solicitado', max_length=30)),
                ('observacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('despacho_retira', models.CharField(blank=True, max_length=50, null=True)),
                ('horario_desde', models.CharField(blank=True, max_length=50, null=True)),
                ('horario_hasta', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='nota_app.clientes')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_creadas', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_creado', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('clase1', models.CharField(blank=True, max_length=100, null=True)),
                ('clase2', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=300)),
                ('rut_proveedor', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('giro', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedores_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidoMateriasPrimas',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('observacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas_creados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas_modificados', to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas', to='nota_app.productos')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas', to='nota_app.proveedores')),
            ],
            options={
                'db_table': 'pedido_materias_primas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_app.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_app.proveedores')),
            ],
            options={
                'unique_together': {('producto', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='SabadoTrabajado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabados_trabajados', to='nota_app.personal')),
                ('sabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_app.sabado')),
            ],
            options={
                'unique_together': {('personal', 'sabado')},
            },
        ),
    ]
