# Generated by Django 5.2.1 on 2025-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='correo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='horario_desde',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='horario_hasta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
