# Generated by Django 5.2.1 on 2025-09-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='num_nota',
            field=models.IntegerField(unique=True),
        ),
    ]
