# Generated by Django 5.2.1 on 2025-08-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfacturas',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
