# Generated by Django 5.2.1 on 2025-08-08 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_creado', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=300)),
                ('rut_proveedor', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('giro', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedores_creados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedores_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('clase1', models.CharField(blank=True, max_length=100, null=True)),
                ('clase2', models.CharField(blank=True, max_length=100, null=True)),
                ('clase3', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos_modificados', to=settings.AUTH_USER_MODEL)),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto_proveedor', to='nota_app.proveedores')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
    ]
