# Generated by Django 5.2.1 on 2025-09-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0002_alter_notas_num_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_productos', to='nota_app.notas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_notas', to='nota_app.productos')),
            ],
            options={
                'db_table': 'nota_producto',
                'unique_together': {('nota', 'producto')},
            },
        ),
    ]
