# Generated by Django 5.2.1 on 2025-05-27 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0002_alter_notas_correo_alter_notas_horario_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='id_usuario_modificacion',
            field=models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notas',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
