# Generated by Django 5.2.1 on 2025-08-11 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0002_personal_proveedores_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabado',
            fields=[
                ('id_sabado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SabadoTrabajado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabados_trabajados', to='nota_app.personal')),
                ('sabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_app.sabado')),
            ],
            options={
                'unique_together': {('personal', 'sabado')},
            },
        ),
    ]
