# Generated by Django 5.2.1 on 2025-09-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0003_notaproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='estado_solicitud',
            field=models.CharField(default='NO SOLICITADO', max_length=30),
        ),
    ]
