# Generated by Django 5.2.1 on 2025-08-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0003_sabado_sabadotrabajado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id_proveedor',
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_app.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota_app.proveedores')),
            ],
            options={
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
