# Generated by Django 5.2.1 on 2025-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0004_alter_notas_estado_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaproducto',
            name='sin_nota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
