# Generated by Django 5.2.1 on 2025-08-13 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0004_remove_productos_id_proveedor_productoproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMateriasPrimas',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_entrega', models.DateField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas', to='nota_app.productos')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas', to='nota_app.proveedores')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas_creados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_modificacion', models.ForeignKey(blank=True, db_column='id_usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido_materias_primas',
                'managed': True,
            },
        ),
    ]
