# Generated by Django 5.2.1 on 2025-09-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0005_notaproducto_sin_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaproducto',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
