# Generated by Django 5.2.1 on 2025-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0005_pedidomateriasprimas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomateriasprimas',
            name='fecha_entrega',
            field=models.DateTimeField(),
        ),
    ]
