# Generated by Django 5.2.1 on 2025-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0006_alter_pedidomateriasprimas_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomateriasprimas',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
