# Generated by Django 5.2.1 on 2025-09-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0006_notaproducto_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notaproducto',
            old_name='sin_nota',
            new_name='tipo',
        ),
    ]
