# Generated by Django 5.2.1 on 2025-09-23 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0007_rename_sin_nota_notaproducto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaproducto',
            name='nota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_productos', to='nota_app.notas'),
        ),
    ]
