# Generated by Django 5.2.1 on 2025-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0007_pedidomateriasprimas_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomateriasprimas',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
    ]
