# Generated by Django 5.2.1 on 2025-09-23 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0008_alter_notaproducto_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaproducto',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_productos', to='nota_app.notas'),
        ),
    ]
