# Generated by Django 5.2.1 on 2025-08-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0009_pdfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='id_pdf',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
