# Generated by Django 5.2.1 on 2025-09-23 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0009_alter_notaproducto_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaproducto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
