# Generated by Django 5.2.1 on 2025-08-20 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0010_alter_pdfdocument_id_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to=settings.AUTH_USER_MODEL),
        ),
    ]
