# Generated by Django 5.2.1 on 2025-09-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0010_notaproducto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaproducto',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
    ]
