# Generated by Django 5.2.1 on 2025-08-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0011_alter_pdfdocument_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='subject',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
