# Generated by Django 5.2.1 on 2025-09-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0011_notaproducto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaproducto',
            name='usuario_creacion',
            field=models.ForeignKey(db_column='usuario_creacion', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nota_producto_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaproducto',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, db_column='usuario_modificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nota_producto_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
