# Generated by Django 5.2.1 on 2025-10-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0012_notaproducto_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomateriasprimas',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidomateriasprimas',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_materias_primas', to='nota_app.proveedores'),
        ),
    ]
