# Generated by Django 5.2.1 on 2025-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0013_notaproducto_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoproveedor',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
    ]
