# Generated by Django 5.2.1 on 2025-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0013_pdfdocumentfacturas_delete_pdfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
    ]
