# Generated by Django 5.2.1 on 2025-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0014_notaproducto_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaproducto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
