# Generated by Django 5.2.1 on 2025-08-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0014_alter_proveedores_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='clase3',
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
