# Generated by Django 5.2.1 on 2025-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0015_remove_productos_clase3_alter_productos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocumentfacturas',
            name='file',
            field=models.FileField(upload_to='facturas/'),
        ),
    ]
