# Generated by Django 5.2.1 on 2025-08-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0016_alter_pdfdocumentfacturas_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=20),
        ),
    ]
