# Generated by Django 5.2.1 on 2025-08-27 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0017_alter_personal_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFacturas',
            fields=[
                ('id_pdf', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='facturas/')),
                ('file_size', models.BigIntegerField()),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(default='NO PAGADO', max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_facturas',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='PDFDocumentFacturas',
        ),
    ]
