# Generated by Django 5.2.1 on 2025-08-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota_app', '0018_documentfacturas_delete_pdfdocumentfacturas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentfacturas',
            old_name='id_pdf',
            new_name='id_factura',
        ),
    ]
